export enum USER_ERROR_CODE {
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_FOOD_CATEGORY = 'INVALID_FOOD_CATEGORY',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
  USER_NOT_AUTHENTICATED = 'USER_NOT_AUTHENTICATED',
}

export enum STORE_ERROR_CODE {
  STORE_NOT_FOUND = 'STORE_NOT_FOUND',
  STORE_ALREADY_EXISTS = 'STORE_ALREADY_EXISTS',
  STORE_NOT_AUTHORIZED = 'STORE_NOT_AUTHORIZED',
  STORE_NOT_AUTHENTICATED = 'STORE_NOT_AUTHENTICATED',
}

export enum MISSION_ERROR_CODE {
  MISSION_NOT_FOUND = 'MISSION_NOT_FOUND',
  MISSION_ALREADY_EXISTS = 'MISSION_ALREADY_EXISTS',
  MISSION_ALREADY_IN_PROGRESS = 'MISSION_ALREADY_IN_PROGRESS',
  MISSION_INVALID_END_AT = 'MISSION_INVALID_END_AT',
  MISSION_NOT_AUTHORIZED = 'MISSION_NOT_AUTHORIZED',
  MISSION_NOT_AUTHENTICATED = 'MISSION_NOT_AUTHENTICATED',
}

export enum REVIEW_ERROR_CODE {
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_AUTHORIZED = 'REVIEW_NOT_AUTHORIZED',
  REVIEW_NOT_AUTHENTICATED = 'REVIEW_NOT_AUTHENTICATED',
  USER_MISSION_MISMATCH = 'USER_MISSION_MISMATCH',
}

export enum LOCATION_ERROR_CODE {
  LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND',
}
